name: ewglobal
channels:
- conda-forge
- defaults
dependencies:
- python=3.10.*
- matplotlib=3.5.*
- numpy=1.22.*
- pip
- scipy=1.8.*
- xarray=2022.*
- ipykernel
- gsw=3.*
- netcdf4=1.5.*
- cmocean
- tqdm
- cartopy=0.20.*
- pydap=3.3.*
- lxml=4.8.*
- jupytext
# - pip: 
    # - global-land-mask